CREATE TABLE IF NOT EXISTS book (
    id INTEGER NOT NULL AUTO_INCREMENT,
    public_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
